Changed lavalink wrapper to lavacoffee
aoijs/aoi.js pull request #305
Opened 2021-11-02 12:41 UTC by Kino7916

## Type
- [ ] Bug Fix
- [ ] Functions: \<Function Name>
- [ ] Callbacks: \<Callback Name>
- [x] Handlers: LavaCommands
- [x] Others: Changed lavalink wrapper to lavacoffee

Dependencies (Third Party Modules) needed: lavacoffee

Want a credit? Discord tag or other social media link: Azusfin#9887 ( package ), Kino#0452 ( implementations )

Referenced Issue: None

## Changelog
- Allows multiple node creations
- Replaying feature ( lavacoffee ), replays the track of player when the used node is disconnected
- Deleted deprecated methods
- Removed strict errors
- Player autocreates when $lavalinkExecute are mentioned
- Changed `loopqueue`, `loopsong` as deprecated methods
- Added `search`, `getsearch`, `addtrack`, `loopmode` methods
- Changed entire method workings, mostly impactful for `play` method
- Changed `play` logic, now developers will have to use `search`, `getsearch`, and `addtrack` to add tracks to the play queue.

2021-11-02 20:00 UTC, Leref requested changes

2021-11-02 20:00 UTC, Leref commented on package.json
> -    "ytdl-core-discord": "^1.3.1"
Music Functions require this.

2021-11-03 03:32 UTC, Kino7916 commented
t> the rewrite is fully broken.

This patch should fix most

2021-11-03 05:41 UTC, Kino7916 commented
Closing for now

2021-11-03 05:41 UTC, closed without merging