Added Reason option for remove/add roles & fixed $interactionDeferUpdate
aoijs/aoi.js pull request #458
Opened 2023-06-23 21:20 UTC by ethann2004

## Type
- [ x] Bug Fix
- [ x] Functions: `$giveRoles`, `$giveRole`, `$takeRoles`, `$takeRole`, `$interactionDeferUpdate`, `$authorAvatar`, `$memberAvatar`, `$userAvatar`, `$userDefaultAvatar`

## Description
I added the `Reason` option for the give/take role functions. I also fixed `$interactionDeferUpdate` return [Object, Object]. Changed `format` to `extension` in all avatar functions since Discord.js v14 renamed that option.

2023-06-25 00:09 UTC, Leref approved these changes

2023-06-25 00:51 UTC, Neodevils commented
Hello @ethann2004! 

I would like to recommend you to **create a pull** request for per file. It will be easier to manage pull requests.

2023-06-25 00:54 UTC, Leref commented
> Hello @ethann2004!
> 
> I would like to recommend you to **create a pull** request for per file/thing. It will be easier to manage pull requests.

It wasn’t hard to read since the whole purpose of this PR was to add `reason` of functions that have support for it.

2023-06-25 05:16 UTC, USERSATOSHI requested changes

2023-06-25 05:16 UTC, USERSATOSHI commented on src/functions/Funcs/interaction/giveRole.js
> +    const [guildID, userID, reason, roleId] = data.inside.splits;
i think reason should be the last field as it can be optional

2023-06-25 05:16 UTC, USERSATOSHI commented on src/functions/Funcs/interaction/takeRole.js
> +    const [guildID, userID, reason, roleId] = data.inside.splits;
same here

2023-06-25 05:16 UTC, USERSATOSHI commented on src/functions/Funcs/user/userAvatar.js
>          dynamic: dynamic === 'true',
this can be changed to forceStatic:  dynamic === 'false'

2023-06-25 05:16 UTC, USERSATOSHI commented on src/functions/Funcs/user/userDefaultAvatar.js
> +    const [userID = d.author?.id, size = 4096, dynamic = 'true', extension] = data.inside.splits;
defaultAvatarUrl doesnt support properties so we can remove image options and just keep userid

2023-06-25 08:29 UTC, ethann2004 commented
@USERSATOSHI I'll edit the files later on when I have time to spare!

2023-06-25 10:59 UTC, USERSATOSHI commented
> @USERSATOSHI I'll edit the files later on when I have time to spare!

Sure np

2023-06-25 20:34 UTC, ethann2004 commented
@USERSATOSHI I think I fixed everything you mention! Let me know if you find something else I can change. I also added the "reason" option in `$setRoles` as I forgot

2023-06-27 12:57 UTC, USERSATOSHI approved these changes

2023-06-27 12:57 UTC, merged