Functions fix
aoijs/aoi.js pull request #501
Opened 2023-11-20 11:06 UTC by LordexDuck3990

Just fixed 2 emoji funcs

2023-11-25 15:06 UTC, LordexDuck3990 commented
![ISC9YzzlR4](https://github.com/AkaruiDevelopment/aoi.js/assets/130374125/8ac46f31-d6a6-4158-bcec-e8c143452c9b)

2023-11-27 19:24 UTC, Leref requested changes

2023-11-27 19:24 UTC, Leref commented on src/handler/parsers.js
> +    let no  = [ "false" ];
This completely can be changed into one array instead of two.

2023-11-27 19:24 UTC, Leref commented on src/handler/parsers.js
> +            let nameofparserorsmtidk = "actionRow";
Rename this variable

2023-11-27 19:24 UTC, Leref commented on src/handler/parsers.js
> +                    var buttons = element.split("{button:").slice(1);
Everything down here should be using let or const instead.

2023-11-27 19:24 UTC, Leref commented on src/handler/parsers.js
> -module.exports = {
There is some files still using these methods

2023-11-27 19:32 UTC, Leref commented on src/handler/parsers.js
> +        ...DataToReturnLol,
Rename

2023-11-28 07:13 UTC, LordexDuck3990 commented
done ig

2023-11-28 16:38 UTC, LordexDuck3990 commented
yeah done

2023-12-03 04:14 UTC, Leref commented
conflicts

2023-12-03 12:02 UTC, closed without merging