math functions
aoijs/aoi.js pull request #535
Opened 2023-12-22 17:16 UTC by aho-emi

## Type
- [ ] Bug Fix
- [ ] Functions: ceil, floor, root, pow
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Dependencies (Third Party Modules) needed: <Name | Github Link> (Maximum: 20MB~ size)

Want a credit? Discord tag or other social media link: <DiscordTag | OtherSocialMediaLink>

Referenced Issue: #NaN (Answer for an issue, if any)

## Description
Pull Request Description Here

2023-12-22 18:39 UTC, USERSATOSHI requested changes

2023-12-22 18:39 UTC, USERSATOSHI commented on src/functions/math/pow.js
> +    data.result = Math.pow(Number(number), Number(power));
Add chaining options so users can chain them like $pow[1;2;3]
so we get Math.pow(Math.pow(1,2),3)

2023-12-22 18:39 UTC, USERSATOSHI commented on src/functions/math/root.js
> +      data.result = number < 0 && root % 2 === 0 ? NaN : Math.pow(Number(number), 1 / Number(root));
Same for this

2023-12-26 15:28 UTC, Leref approved these changes

2023-12-26 15:28 UTC, merged