Bump discordjs
aoijs/aoi.js pull request #588
Opened 2024-05-05 02:44 UTC by Faf4a

Bumps `discord.js` to `14.15.1`

Adds:
- Polls
	- SEND_POLLS (permission)
	- `$sendPoll`
	- `$endPoll`
	- `$getPollVotes`
- SKU's
	- Events 
		- `entitlementCreate`
		- `entitlementUpdate`
		- `entitlementDelete`
- Guild Scheduled Events
	-  Intents
		- `GuildScheduledEvents` 
	- Events
		- `onGuildScheduledCreate`
		- `onGuildScheduledUpdate`
		- `onGuildScheduledDelete`
		- `onGuildScheduledUserAdd`

Refactor
- `$createBanner` (use client.user.setBanner())

2024-05-06 05:18 UTC, USERSATOSHI submitted a review, later dismissed

2024-05-06 05:18 UTC, USERSATOSHI commented on src/functions/message/createPoll.js
> +
add support for json too 
with { name: name,  value:value } for ig either 1 in that we use array or u can do for each ;

2024-05-06 10:20 UTC, Faf4a commented
All three of those need oauth to work properly, no point in having them anymore.

2024-05-07 20:34 UTC, USERSATOSHI submitted a review, later dismissed

2024-05-07 20:34 UTC, USERSATOSHI commented on src/functions/message/createPoll.js
> +
what i meant was for answers not for everything

2024-05-09 19:36 UTC, Leref requested changes

2024-05-09 19:36 UTC, Leref commented on src/functions/interaction/setApplicationCommandPermissions.js
Removed?

2024-05-09 19:36 UTC, Leref commented on src/functions/interaction/removeApplicationCommandPermissions.js
Removed?

2024-05-09 19:36 UTC, Leref commented on src/functions/interaction/addApplicationCommandPermissions.js
Removed?

2024-05-09 19:36 UTC, Leref commented on src/utils/Constants.js
Removed?

2024-05-10 17:16 UTC, USERSATOSHI commented
> All three of those need oauth to work properly, no point in having them anymore.

which ones?

2024-05-10 17:37 UTC, Faf4a commented
> > All three of those need oauth to work properly, no point in having them anymore.
> 
> which ones?

removeappperms, addappperms, setappperms

all require oauth

2024-05-12 22:17 UTC, Leref commented
Still need more information on the auth?

2024-05-12 23:08 UTC, closed without merging