Fixed arraySort.js
aoijs/aoi.js pull request #633
Opened 2024-07-31 16:40 UTC by LightnerDev

## Type
- [X] Bug Fix
- [X] Functions: $arraySort
- [ ] Callbacks: \<Callback Name>
- [ ] Handlers: \<Handler Type>
- [ ] Others: \______

Dependencies (Third Party Modules) needed: <Name | Github Link> (Maximum: 20MB~ size)

Want a credit? Discord tag or other social media link: lightner.

Referenced Issue: Only reported in Discord (Answer for an issue, if any)

## Description
Fix $arraySort to actually sort array instead of treating each value as equal

2024-07-31 19:47 UTC, Faf4a requested changes
thanks for the pr! please take a look at the review I left behind

2024-07-31 19:47 UTC, Faf4a commented on src/functions/arraySort.js
>    );
Maybe doing it like this:

```js
.sort((a, b) =>
    typeof a === "number" && typeof b === "number" ? a - b :
    typeof a === "string" && typeof b === "string" ? a.localeCompare(b) :
    typeof a === "number" ? -1 : 1
);
```

is more readable and robust? you could use .reverse() at the end to reverse the array if type is desc

2024-08-03 15:47 UTC, LightnerDev commented
I didn't exactly follow the way you said to do it in the comment because this way of sorting the array emulates the same way that arrays are sorted in javascript

2024-08-04 05:38 UTC, Faf4a approved these changes

2024-08-08 16:48 UTC, Leref approved these changes

2024-08-08 16:48 UTC, merged