Update ForEachObjectArray.js
aoijs/aoi.js pull request #675
Opened 2024-10-26 20:09 UTC by supremesupreme

## Description

Fixed it in a case where it wasnt looping thought the arrays

Fixes # (issue number / __remove this line__ if no issue is to be referenced)

## Type of change

Please check options that describe your Pull Request:

- [x] Bug fix (non-breaking change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

---

- [x] My code follows the style guidelines of this project
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-26 23:32 UTC, Faf4a approved these changes

2024-11-12 21:46 UTC, USERSATOSHI requested changes

2024-11-12 21:46 UTC, USERSATOSHI commented on src/functions/forEachObjectArray.js
> +        if (d.data.objects[name][property].hasOwnProperty(key)) {
need a check before this for loop to see if d.data.objects[name][property] is an iterable else it will error out

2025-01-02 07:16 UTC, Faf4a commented
stale

2025-01-02 07:16 UTC, closed without merging